### ISSUE TITLE
integration test incorrectly modifies 

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#189]
this chunk modifies my `parameter_files/WebParameters_2dii.yml`, which makes the integration test fail, and causes more problems with my clone

https://github.com/2DegreesInvesting/PACTA_analysis/blob/ef5e55aa5fc3d2a3ff21dd6d3bda2c72b5fee861/integration-test.Rmd#L201-L230 

it changes my `parameter_files/WebParameters_2dii.yml` from:
```
default:
    paths:
        # Prefer "../PACTA_analysis/" -- not "./" nor "/path/to/PACTA_analysis"
        project_location_ext: ../PACTA_analysis/
        data_location_ext: ../pacta-data/2019Q4/
        template_location: ../create_interactive_report/
        stress_test_location: ../StressTestingModelDev/
    parameters:
        project_name: working_dir
        twodii_internal: FALSE
        new_data: FALSE
```

to
```
default:
    paths:
        # Prefer "../PACTA_analysis/" -- not "./" nor "/path/to/PACTA_analysis"
        project_location_ext: /Users/cj2dii/Documents/Git/PACTA_analysis"/
        data_location_ext: /Users/cj2dii/Documents/Git/pacta-data/2019Q4/
        template_location: /Users/cj2dii/Documents/Git/create_interactive_report/
        stress_test_location: /Users/cj2dii/Documents/Git/StressTestingModelDev/
    parameters:
        project_name: working_dir
        twodii_internal: FALSE
        new_data: FALSE
```
