### ISSUE TITLE
update test-r-scripts.yaml workflow to work with recent web tool changes

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#264]
the failing tests since #261 reveal...
1. `pandoc` will need to be installed in the worker defined here [.github/workflows/test-r-scripts.yaml](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/.github/workflows/test-r-scripts.yaml)
2. probably other stuff for latex will need to be installed also
3. also likely that some additional R pkgs will need to be installed, e.g. rmarkdown and bookdown
4. I can also predict that it will also have to clone the new 2DegreesInvesting/user_results repo

should we try to do that here in this PR before it merges, or better to open a separate issue?

_Originally posted by @cjyetman in https://github.com/2DegreesInvesting/PACTA_analysis/pull/261#issuecomment-716809041_

**Comment by cjyetman** [comment]
in here [.github/workflows/test-r-scripts.yaml](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/.github/workflows/test-r-scripts.yaml) we're gonna need to add...
```
      - name: Checkout user_results
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/user_results
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: user_results
```

**Comment by cjyetman** [comment]
apparently you can directly reference a docker container, which might be ideal for testing our web tools in our specially made docker image.... for example...
```
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: docker://alpine:3.8
```
